<?php

declare(strict_types=1);

namespace ElasticKit\Index;

use Elastic\Elasticsearch\Exception\ClientResponseException;
use RuntimeException;
use stdClass;

/**
 * Zero-downtime index rebuild: create backing index, import data, swap alias.
 *
 * $name is always the app-facing name. After rebuild, $name becomes an alias
 * pointing to a backing index generated by rebuildName().
 *
 * @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
 */
class Rebuild
{
    /**
     * Lock index name.
     */
    private const LOCK_INDEX = '.ek_locks';

    /**
     * @var int
     */
    private int $batchSize = 1000;

    /**
     * @var callable|null
     */
    private $errorHandler = null;

    /**
     * @var bool
     */
    private bool $allowEmpty = false;

    /**
     * @var callable|iterable<int, array<string, mixed>>|null
     */
    private $dataSource;

    public function __construct(
        private readonly Index $index
    ) {
    }

    /**
     * Set the batch size for bulk import. Defaults to 1000.
     *
     * @param int $size
     * @return $this
     */
    public function batchSize(int $size): static
    {
        $this->batchSize = $size;
        return $this;
    }

    /**
     * Set a callback to handle bulk import errors.
     *
     * Forwards to Bulk::onError(): the callback receives the raw ES response, the
     * full batch body, and a fresh Bulk bound to the new backing index. Extract
     * the failures from $body via $response and re-import them on the Bulk, or
     * return to drop them and continue, or throw to abort (the new index is then
     * deleted). Without a handler, any import error aborts the rebuild.
     *
     * @param callable $handler function (array $response, array $body, Bulk $newbulk): void
     * @return $this
     */
    public function onError(callable $handler): static
    {
        $this->errorHandler = $handler;
        return $this;
    }

    /**
     * Allow importing zero documents without throwing. Defaults to false.
     *
     * @param bool $allow
     * @return $this
     */
    public function allowEmpty(bool $allow = true): static
    {
        $this->allowEmpty = $allow;
        return $this;
    }

    /**
     * Set a custom data source. Accepts a callable or iterable.
     * Defaults to Index::source() when not set.
     *
     * @param callable|iterable<int, array<string, mixed>> $source
     * @return $this
     */
    public function source(callable|iterable $source): static
    {
        $this->dataSource = $source;
        return $this;
    }

    /**
     * Run the rebuild: create backing index -> import data -> swap alias.
     *
     * Handles three scenarios:
     * - $name is already an alias: atomic swap (zero downtime)
     * - $name is a real index: throws RuntimeException (convert to alias mode first)
     * - $name does not exist: create alias pointing to new backing index
     *
     * The lock is always released: on failure doRun()'s exception is rethrown
     * (never masked); on success a release failure surfaces as a RuntimeException
     * noting the rebuild completed but the lock is stale.
     *
     * @param array<string, mixed> $context user-defined context passed to source()
     * @return array{newIndex: string, oldIndex: string|null}
     */
    public function run(array $context = []): array
    {
        $this->acquireLock();

        try {
            $result = $this->doRun($context);
        } catch (\Throwable $e) {
            try {
                $this->releaseLock();
            } catch (\Throwable) {
                // Ignore release failure; the original exception propagates below.
            }
            throw $e;
        }

        // Success: data is swapped, so a release failure means only the lock is stale.
        try {
            $this->releaseLock();
        } catch (\Throwable $e) {
            throw new RuntimeException(
                "Rebuild for [{$this->index->name()}] succeeded but the lock could not be released. "
                . "Data is already swapped to the new index. Call forceUnlock() to clear the stale lock.",
                0,
                $e
            );
        }

        return $result;
    }

    /**
     * Forcibly remove a stale lock left by a crashed rebuild.
     *
     * Under normal circumstances the lock is released automatically by run().
     * Call this only when a previous rebuild crashed and the lock persists.
     *
     * Idempotent: a 404 (lock index or document missing) is treated as success.
     */
    public function forceUnlock(): void
    {
        try {
            $this->index->getClient()->delete([
                'index' => self::LOCK_INDEX,
                'id' => $this->index->name(),
            ]);
        } catch (ClientResponseException $e) {
            if ($e->getResponse()->getStatusCode() !== 404) {
                throw $e;
            }
        }
    }

    /**
     * Check whether a rebuild lock is currently held for this index.
     *
     * Returns false only on a real 404; other ES errors propagate so an
     * unreachable cluster is never mistaken for an unlocked index.
     *
     * @return bool
     */
    public function isLocked(): bool
    {
        try {
            return $this->index->getClient()->exists([
                'index' => self::LOCK_INDEX,
                'id' => $this->index->name(),
            ])->asBool();
        } catch (ClientResponseException $e) {
            if ($e->getResponse()->getStatusCode() === 404) {
                return false;
            }
            throw $e;
        }
    }

    /**
     * Delete a specific backing index by name.
     *
     * @param string $indexName the backing index to delete
     */
    public function clean(string $indexName): void
    {
        $this->index->getClient()->indices()->delete([
            'index' => $indexName,
        ]);
    }

    /**
     * Rollback alias to a specific previous backing index.
     *
     * @param string $targetIndex the backing index to roll back to
     * @return string the index name that was rolled back from
     * @throws RuntimeException if alias or target index does not exist
     */
    public function rollback(string $targetIndex): string
    {
        $name = $this->index->name();
        $client = $this->index->getClient()->indices();

        $currentList = array_keys($client->getAlias(['name' => $name])->asArray());
        if (empty($currentList)) {
            throw new RuntimeException("No index found for alias [{$name}]");
        }

        if (!$client->exists(['index' => $targetIndex])->asBool()) {
            throw new RuntimeException("Target index [{$targetIndex}] does not exist");
        }

        $actions = [];
        foreach ($currentList as $idx) {
            $actions[] = ['remove' => ['index' => $idx, 'alias' => $name]];
        }
        $actions[] = ['add' => ['index' => $targetIndex, 'alias' => $name]];

        $client->updateAliases([
            'body' => [
                'actions' => $actions,
            ],
        ]);

        return $currentList[0];
    }

    /**
     * Execute the rebuild logic (called after lock is acquired).
     *
     * @param array<string, mixed> $context
     * @return array{newIndex: string, oldIndex: string|null}
     */
    private function doRun(array $context): array
    {
        $name = $this->index->name();
        $client = $this->index->getClient()->indices();

        EventDispatcher::dispatch(new Event('rebuild.run.before', $name));

        $newIndex = $this->createIndex();

        try {
            $this->import($newIndex, $context);
        } catch (\Throwable $e) {
            $client->delete(['index' => $newIndex]);
            throw $e;
        }

        $client->refresh(['index' => $newIndex]);

        $oldIndex = null;

        if ($client->existsAlias(['name' => $name])->asBool()) {
            $oldIndices = array_keys($client->getAlias(['name' => $name])->asArray());
            $oldIndex = $oldIndices[0] ?? null;
            $actions = [];
            foreach ($oldIndices as $idx) {
                $actions[] = ['remove' => ['index' => $idx, 'alias' => $name]];
            }
            $actions[] = ['add' => ['index' => $newIndex, 'alias' => $name]];
            $client->updateAliases(['body' => ['actions' => $actions]]);
        } elseif ($client->exists(['index' => $name])->asBool()) {
            $client->delete(['index' => $newIndex]);
            throw new RuntimeException(
                "Index [{$name}] is a real index, not an alias. "
                . "Rebuild requires an alias to swap atomically. "
                . "Delete the index manually or convert it to alias mode before running rebuild."
            );
        } else {
            $client->putAlias(['index' => $newIndex, 'name' => $name]);
        }

        $e = new Event('rebuild.run.after', $name);
        $e->newIndex = $newIndex;
        $e->oldIndex = $oldIndex;
        EventDispatcher::dispatch($e);

        return ['newIndex' => $newIndex, 'oldIndex' => $oldIndex];
    }

    /**
     * Acquire the distributed lock using ES document create (op_type=create).
     *
     * @throws RuntimeException if the lock is already held
     */
    private function acquireLock(): void
    {
        $this->ensureLockIndex();

        $name = $this->index->name();

        try {
            $this->index->getClient()->index([
                'index' => self::LOCK_INDEX,
                'id' => $name,
                'body' => ['locked_at' => date(\DateTimeInterface::ATOM)],
                'op_type' => 'create',
            ]);
        } catch (ClientResponseException $e) {
            if ($e->getResponse()->getStatusCode() === 409) {
                throw new RuntimeException(
                    "Rebuild for [{$name}] is already running. "
                    . "Call forceUnlock() if the previous rebuild crashed."
                );
            }
            throw $e;
        }
    }

    /**
     * Release the lock. Idempotent: only 404 is swallowed; other failures
     * (transport, 5xx) propagate so a stale lock stays detectable.
     *
     * @throws ClientResponseException for any non-404 failure
     */
    private function releaseLock(): void
    {
        try {
            $this->index->getClient()->delete([
                'index' => self::LOCK_INDEX,
                'id' => $this->index->name(),
            ]);
        } catch (ClientResponseException $e) {
            if ($e->getResponse()->getStatusCode() === 404) {
                return; // Lock already gone — idempotent
            }
            throw $e;
        }
    }

    /**
     * Ensure the lock index exists. Handles concurrent creation races.
     */
    private function ensureLockIndex(): void
    {
        $indices = $this->index->getClient()->indices();

        if ($indices->exists(['index' => self::LOCK_INDEX])->asBool()) {
            return;
        }

        try {
            $indices->create([
                'index' => self::LOCK_INDEX,
                'body' => [
                    'settings' => [
                        'number_of_shards' => 1,
                        'number_of_replicas' => 0,
                        'index.hidden' => true,
                    ],
                ],
            ]);
        } catch (ClientResponseException $e) {
            // Race: another process may have created it concurrently
            if ($indices->exists(['index' => self::LOCK_INDEX])->asBool()) {
                return;
            }
            throw $e;
        }
    }

    /**
     * Create a new backing index using mappings/settings from the Index subclass.
     *
     * @return string the new backing index name
     */
    protected function createIndex(): string
    {
        $newIndex = $this->index->rebuildName();
        $mappings = $this->index->mappings();
        $settings = $this->index->settings();

        $this->index->getClient()->indices()->create([
            'index' => $newIndex,
            'body' => [
                'mappings' => empty($mappings) ? new stdClass() : $mappings,
                'settings' => empty($settings) ? new stdClass() : $settings,
            ],
        ]);

        return $newIndex;
    }

    /**
     * Import data into the target index.
     *
     * @param string $newIndex
     * @param array<string, mixed> $context
     */
    protected function import(string $newIndex, array $context): void
    {
        if ($this->dataSource !== null) {
            $items = is_callable($this->dataSource) ? ($this->dataSource)($context) : $this->dataSource;
        } else {
            $items = $this->index->source($context);
        }

        $bulk = (new Bulk($this->index))->target($newIndex)->batchSize($this->batchSize);
        if ($this->errorHandler) {
            $bulk->onError($this->errorHandler);
        }

        $count = 0;
        foreach ($items as $id => $doc) {
            if (!is_array($doc)) {
                throw new RuntimeException(
                    "source() must yield [id => document] pairs, got non-array value for key [{$id}]. "
                    . "Expected: yield \$id => ['field' => 'value'], got \$id => " . gettype($doc)
                );
            }
            $bulk->index($id, $doc);
            $count++;
        }

        if ($count === 0 && !$this->allowEmpty) {
            throw new RuntimeException(
                "Rebuild imported 0 documents for index [{$newIndex}]. "
                . "Call allowEmpty() if this is intentional."
            );
        }

        $bulk->flush();
    }
}
