<?php

namespace ElasticKit\Index;

use Elastic\Elasticsearch\Exception\ClientResponseException;
use RuntimeException;
use stdClass;

/**
 * Zero-downtime index rebuild: create backing index, import data, swap alias.
 *
 * $name is always the app-facing name. After rebuild, $name becomes an alias
 * pointing to a backing index generated by rebuildName().
 */
class Rebuild
{
    /**
     * Lock index name.
     */
    private const LOCK_INDEX = '.ek_locks';

    /**
     * @var Index
     */
    private $index;

    /**
     * @var int
     */
    private $batchSize = 1000;

    /**
     * @var callable|null
     */
    private $errorHandler = null;

    /**
     * @var bool
     */
    private $allowEmpty = false;

    /**
     * @var callable|\Iterator<int, array<string, mixed>>|null
     */
    private $dataSource;

    /**
     * @param Index $index
     */
    public function __construct(Index $index)
    {
        $this->index = $index;
    }

    /**
     * Set the batch size for bulk import. Defaults to 1000.
     *
     * @param int $size
     * @return $this
     */
    public function batchSize($size)
    {
        $this->batchSize = $size;
        return $this;
    }

    /**
     * Set a callback to handle bulk import errors.
     *
     * The callback receives the raw ES response. To continue the rebuild, simply
     * return without throwing. To abort, throw an exception from the callback.
     * Without an error handler, import errors cause the rebuild to abort.
     *
     * @param callable $handler function (array $response): void
     * @return $this
     */
    public function onError($handler)
    {
        $this->errorHandler = $handler;
        return $this;
    }

    /**
     * Allow importing zero documents without throwing. Defaults to false.
     *
     * @param bool $allow
     * @return $this
     */
    public function allowEmpty($allow = true)
    {
        $this->allowEmpty = $allow;
        return $this;
    }

    /**
     * Set a custom data source. Accepts a callable or iterable.
     * Defaults to Index::source() when not set.
     *
     * @param callable|\Iterator<int, array<string, mixed>> $source
     * @return $this
     */
    public function source($source)
    {
        $this->dataSource = $source;
        return $this;
    }

    /**
     * Run the rebuild: create backing index -> import data -> swap alias.
     *
     * Handles three scenarios:
     * - $name is already an alias: atomic swap (zero downtime)
     * - $name is a real index: throws RuntimeException (convert to alias mode first)
     * - $name does not exist: create alias pointing to new backing index
     *
     * @param array<string, mixed> $context user-defined context passed to source()
     * @return array{newIndex: string, oldIndex: string|null}
     */
    public function run(array $context = [])
    {
        $this->acquireLock();

        try {
            $result = $this->doRun($context);
        } finally {
            $this->releaseLock();
        }

        return $result;
    }

    /**
     * Forcibly remove a stale lock left by a crashed rebuild.
     *
     * Under normal circumstances the lock is released automatically by run().
     * Call this only when a previous rebuild crashed and the lock persists.
     */
    public function forceUnlock(): void
    {
        $this->releaseLock();
    }

    /**
     * Check whether a rebuild lock is currently held for this index.
     *
     * @return bool
     */
    public function isLocked(): bool
    {
        try {
            return $this->index->getClient()->exists([
                'index' => self::LOCK_INDEX,
                'id' => $this->index->name(),
            ])->asBool();
        } catch (ClientResponseException $e) {
            return false;
        }
    }

    /**
     * Delete a specific backing index by name.
     *
     * @param string $indexName the backing index to delete
     */
    public function clean(string $indexName): void
    {
        $this->index->getClient()->indices()->delete([
            'index' => $indexName,
        ]);
    }

    /**
     * Rollback alias to a specific previous backing index.
     *
     * @param string $targetIndex the backing index to roll back to
     * @return string the index name that was rolled back from
     * @throws RuntimeException if alias or target index does not exist
     */
    public function rollback(string $targetIndex): string
    {
        $name = $this->index->name();
        $client = $this->index->getClient()->indices();

        $currentList = array_keys($client->getAlias(['name' => $name])->asArray());
        if (empty($currentList)) {
            throw new RuntimeException("No index found for alias [{$name}]");
        }

        if (!$client->exists(['index' => $targetIndex])->asBool()) {
            throw new RuntimeException("Target index [{$targetIndex}] does not exist");
        }

        $actions = [];
        foreach ($currentList as $idx) {
            $actions[] = ['remove' => ['index' => $idx, 'alias' => $name]];
        }
        $actions[] = ['add' => ['index' => $targetIndex, 'alias' => $name]];

        $client->updateAliases([
            'body' => [
                'actions' => $actions,
            ],
        ]);

        return $currentList[0];
    }

    /**
     * Execute the rebuild logic (called after lock is acquired).
     *
     * @param array<string, mixed> $context
     * @return array{newIndex: string, oldIndex: string|null}
     */
    private function doRun(array $context): array
    {
        $name = $this->index->name();
        $client = $this->index->getClient()->indices();

        Index::dispatch(new Event('rebuild.run.before', $name));

        $newName = $this->createIndex();

        try {
            $this->import($newName, $context);
        } catch (\Throwable $e) {
            $client->delete(['index' => $newName]);
            throw $e;
        }

        $client->refresh(['index' => $newName]);

        $oldIndex = null;

        if ($client->existsAlias(['name' => $name])->asBool()) {
            $oldIndices = array_keys($client->getAlias(['name' => $name])->asArray());
            $oldIndex = $oldIndices[0] ?? null;
            $actions = [];
            foreach ($oldIndices as $idx) {
                $actions[] = ['remove' => ['index' => $idx, 'alias' => $name]];
            }
            $actions[] = ['add' => ['index' => $newName, 'alias' => $name]];
            $client->updateAliases(['body' => ['actions' => $actions]]);
        } elseif ($client->exists(['index' => $name])->asBool()) {
            $client->delete(['index' => $newName]);
            throw new RuntimeException(
                "Index [{$name}] is a real index, not an alias. "
                . "Rebuild requires an alias to swap atomically. "
                . "Delete the index manually or convert it to alias mode before running rebuild."
            );
        } else {
            $client->putAlias(['index' => $newName, 'name' => $name]);
        }

        $e = new Event('rebuild.run.after', $name);
        $e->newIndex = $newName;
        $e->oldIndex = $oldIndex;
        Index::dispatch($e);

        return ['newIndex' => $newName, 'oldIndex' => $oldIndex];
    }

    /**
     * Acquire the distributed lock using ES document create (op_type=create).
     *
     * @throws RuntimeException if the lock is already held
     */
    private function acquireLock(): void
    {
        $this->ensureLockIndex();

        $name = $this->index->name();

        try {
            $this->index->getClient()->index([
                'index' => self::LOCK_INDEX,
                'id' => $name,
                'body' => ['locked_at' => date(\DateTimeInterface::ATOM)],
                'op_type' => 'create',
            ]);
        } catch (ClientResponseException $e) {
            if ($e->getResponse()->getStatusCode() === 409) {
                throw new RuntimeException(
                    "Rebuild for [{$name}] is already running. "
                    . "Call forceUnlock() if the previous rebuild crashed."
                );
            }
            throw $e;
        }
    }

    /**
     * Release the distributed lock. Idempotent — silently ignores 404.
     */
    private function releaseLock(): void
    {
        try {
            $this->index->getClient()->delete([
                'index' => self::LOCK_INDEX,
                'id' => $this->index->name(),
            ]);
        } catch (ClientResponseException $e) {
            if ($e->getResponse()->getStatusCode() !== 404) {
                throw $e;
            }
            // Lock already gone — idempotent
        } catch (\Throwable $e) {
            // Swallow transport / server errors in finally to avoid masking the original exception
        }
    }

    /**
     * Ensure the lock index exists. Handles concurrent creation races.
     */
    private function ensureLockIndex(): void
    {
        $indices = $this->index->getClient()->indices();

        if ($indices->exists(['index' => self::LOCK_INDEX])->asBool()) {
            return;
        }

        try {
            $indices->create([
                'index' => self::LOCK_INDEX,
                'body' => [
                    'settings' => [
                        'number_of_shards' => 1,
                        'number_of_replicas' => 0,
                        'index.hidden' => true,
                    ],
                ],
            ]);
        } catch (ClientResponseException $e) {
            // Race: another process may have created it concurrently
            if ($indices->exists(['index' => self::LOCK_INDEX])->asBool()) {
                return;
            }
            throw $e;
        }
    }

    /**
     * Create a new backing index using mappings/settings from the Index subclass.
     *
     * @return string the new backing index name
     */
    protected function createIndex()
    {
        $newName = $this->index->rebuildName();
        $mappings = $this->index->mappings();
        $settings = $this->index->settings();

        $this->index->getClient()->indices()->create([
            'index' => $newName,
            'body' => [
                'mappings' => empty($mappings) ? new stdClass() : $mappings,
                'settings' => empty($settings) ? new stdClass() : $settings,
            ],
        ]);

        return $newName;
    }

    /**
     * Import data into the target index.
     *
     * @param string $newName
     * @param array<string, mixed> $context
     */
    protected function import($newName, array $context): void
    {
        if ($this->dataSource !== null) {
            $items = is_callable($this->dataSource) ? ($this->dataSource)($context) : $this->dataSource;
        } else {
            $items = $this->index->source($context);
        }

        $bulk = (new Bulk($this->index))->target($newName)->batchSize($this->batchSize);
        if ($this->errorHandler) {
            $bulk->onError($this->errorHandler);
        }

        $count = 0;
        foreach ($items as $id => $doc) {
            if (!is_array($doc)) {
                throw new RuntimeException(
                    "source() must yield [id => document] pairs, got non-array value for key [{$id}]. "
                    . "Expected: yield \$id => ['field' => 'value'], got \$id => " . gettype($doc)
                );
            }
            $bulk->index($id, $doc);
            $count++;
        }

        if ($count === 0 && !$this->allowEmpty) {
            throw new RuntimeException(
                "Rebuild imported 0 documents for index [{$newName}]. "
                . "Call allowEmpty() if this is intentional."
            );
        }

        $bulk->execute();
    }
}
